import { PickupKind } from '../game/queen-game';
import { SpritePalette } from './sprites';

/**
 * Objetos del tablero en 16×16, con las mismas letras que las piezas:
 * o contorno, b cuerpo, h brillo, s sombra, g detalle. Un punto es transparente.
 */
export const FX_SPRITES: Record<PickupKind | 'bomb', string[]> = {
  clock: [
    '................',
    '...oooooooooo...',
    '...osssssssso...',
    '....ohhhhhho....',
    '....ohbbbbho....',
    '.....ohbbho.....',
    '......ohbo......',
    '.......oo.......',
    '......ohho......',
    '.....ohhbho.....',
    '....ohhbbbho....',
    '....ohbbbbbo....',
    '...osssssssso...',
    '...oooooooooo...',
    '................',
    '................',
  ],
  bolt: [
    '................',
    '.........oooo...',
    '........ohbbo...',
    '.......ohbbo....',
    '......ohbbo.....',
    '.....ohbbo......',
    '....ohbbbbbbo...',
    '....oooobbbo....',
    '.......obbo.....',
    '......obbo......',
    '.....obbo.......',
    '....obso........',
    '...obo..........',
    '...oo...........',
    '................',
    '................',
  ],
  star: [
    '................',
    '.......oo.......',
    '......ohbo......',
    '......ohbo......',
    '.....ohbbbo.....',
    'ooooohbbbbboooo.',
    'obhhhbbbbbbbbbo.',
    '.obbbbbgbgbbbo..',
    '..obbbbbbbbbo...',
    '...obbbbbbbo....',
    '...obbbsbbbo....',
    '..obbbsosbbbo...',
    '..obbso.osbbo...',
    '.obso.....osbo..',
    '.oo.........oo..',
    '................',
  ],
  chest: [
    '................',
    '................',
    '................',
    '...oooooooooo...',
    '..ohhhhhhhhhho..',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.oooooooggooooo.',
    '.ossssssggsssso.',
    '.osbbbbbggbbbso.',
    '.osbbbbbbbbbbso.',
    '.osbbbbbbbbbbso.',
    '.osssssssssssso.',
    '.oooooooooooooo.',
    '................',
    '................',
  ],
  bomb: [
    '..........g.....',
    '.........g.g....',
    '..........g.....',
    '.........o......',
    '........oo......',
    '.....oooooo.....',
    '....obbbbbbo....',
    '...obhhbbbbbo...',
    '...obhbbbbbbo...',
    '...obbbbbbbbo...',
    '...obbbbbbbbo...',
    '...obbbbbbbso...',
    '....obbbbbso....',
    '.....oooooo.....',
    '................',
    '................',
  ],
};

export const FX_PALETTES: Record<PickupKind | 'bomb', SpritePalette> = {
  clock: { b: '#ffd25a', h: '#c2f4ff', s: '#8a4f2e', g: '#ffd25a' },
  bolt: { b: '#62f2ff', h: '#ffffff', s: '#1a8fb0', g: '#62f2ff' },
  star: { b: '#ff59c7', h: '#ffd6f0', s: '#a3207a', g: '#ffffff' },
  chest: { b: '#a8693a', h: '#ffd25a', s: '#5e3214', g: '#ffd25a' },
  bomb: { b: '#2a2233', h: '#6a5a7e', s: '#120c18', g: '#ffd25a' },
};

/** Paleta de las piezas de oro macizo: amarillo limón con gemas cian, para no confundirlas con la reina. */
export const GOLDEN_PALETTE: SpritePalette = { b: '#f5e03a', h: '#fffbe0', s: '#b08a00', g: '#2fc4ef' };
